[package]
name = "rustapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "23.0.1"
serde = "1.0.160"
serde_derive = "1.0.160"
serde_json = "1.0.96"
sqlite = "0.30.4"
ureq = "2.6.2"
